### ISSUE TITLE
 Remote end closed connection without response

### ISSUE THREAD

**Issue by guiscaranse** [fhamborg/news-please#66] opened 2018-07-08 22:33 UTC
I've been trying to scrape some news articles but [this one](https://capricho.abril.com.br/famosos/bruna-marquezine-nao-quer-renovar-contrato-com-a-globo-diz-colunista/) is returning `http.client.RemoteDisconnected: Remote end closed connection without response`. I don't think this is a issue with the website or my code, because using [Goose3](https://github.com/goose3/goose3/) just works. 
I don't have any clue why this is happening.

**Comment by fhamborg** [comment] 2018-07-09 08:42
Please provide a minimalist working example, and include your OS, Py version and news-please version.

**Comment by guiscaranse** [comment] 2018-07-09 14:36
```python
article = NewsPlease.from_url("https://capricho.abril.com.br/famosos/bruna-marquezine-nao-quer-renovar-contrato-com-a-globo-diz-colunista/")
print(str(article.get_serializable_dict()))
```

Windows 10, Python 3.6, news-please latest (pip)

**Comment by fhamborg** [comment] 2018-07-09 15:06
I can reproduce the error. However, according to several sources, e.g., https://stackoverflow.com/a/48105794/, this is an error caused by the HTTP server behaving non-standard-compliant, hence we will not provide a fix for this. You are very welcome to provide a fix and pull request to this issue, though :-)

**Closed by fhamborg** 2018-07-09 15:06 UTC
