### ISSUE TITLE
CommonCrawl: Start and End Date Not Working

### ISSUE THREAD

**Issue by ozgurakyazi** [fhamborg/news-please#142] opened 2020-04-08 20:00 UTC
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).

* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* Did not see any related issue.

**Describe the bug**
Even though I assign valid datetime to the below variables, the warc files are downloaded always starting from a very early time period. 

**To Reproduce**
clone repository

- In newsplease/examples/commoncrawl.py, change following lines:

       my_filter_valid_hosts =["elrancaguino.cl"]
       my_filter_start_date = datetime.datetime(2020, 2, 1)
       my_filter_end_date = datetime.datetime(2020, 2, 5)  
- install awscli wit pip
- run the changed script

see logs:
processed = 1, remaining = 9323, total = 9326
INFO:newsplease.crawler.commoncrawl_extractor:downloading https://commoncrawl.s3.amazonaws.com/crawl-data/CC-NEWS/2016/08/CC-NEWS-20160827145159-00003.warc.gz

**Expected behavior**
Instead of start downloading from 2016, it should download only in 2020 February, which is the specified date.

**Log**
processed = 1, remaining = 9323, total = 9326
INFO:newsplease.crawler.commoncrawl_extractor:downloading https://commoncrawl.s3.amazonaws.com/crawl-data/CC-NEWS/2016/08/CC-NEWS-20160827145159-00003.warc.gz

**Versions (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)
 - Python Version 3.7
 - news-please Version: I do not see any versions. So commit: 39aff553beefe30dac3d359201294291a9f6f57e

**Comment by fhamborg** [comment] 2020-04-10 07:20
Unfortunately, this is expected behaviour and cannot be avoided. Reason is that the datestamp in the filenames of commoncrawl's WARC files, e.g., 2016-08-27 in `https://commoncrawl.s3.amazonaws.com/crawl-data/CC-NEWS/2016/08/CC-NEWS-20160827145159-00003.warc.gz` only indicates when the WARC file was created but *do not* allow to conclude anything about the content, i.e., the publisher date can be (will be) different. In fact, when my team processed all WARC files some time ago, we had some cases where the WARC filename was created in 2018, but contained also articles from 2002.

Thus, news-please has to process all WARC files, extract the article information and only then can decide - based on your date filter settings - if an article is kept or discarded.

**Comment by fhamborg** [comment] 2020-04-10 07:21
Feel very free to reopen the issue in case you have more questions or - even better - you see a way to improve the efficiency in this case :-)

**Comment by ozgurakyazi** [comment] 2020-04-10 07:55
Thank you for this very helpful information. As you already processed it, I would like to ask one more question.

For example, if a WARC file composed in 2016-08, I suppose it cannot contain any articles from future, 2017 for example. I dont know the current implementation but thinking from my single example (this can be a mistake :) ), when asked for an article from 2020, downloading from 2016 sounds unnecessary.  At least we can restrict the download start date. Here is a possible logic:
|:u ---> WARC file upload date, u is id of file.
x---> Requested start date of articles

---- |:1 ---- |:2 ---- |:3 ----x-- |:4 ----- |:5

In this case start downloading from |:4 .

A possible case which could discard this logic: If commoncrawl updates WARC files after creating it, and keeping the initial timestamp on the file name fixed, then the WARC file contains articles from future (compared to its timestamp) and the logic does not work.

Sorry for this long writing,
Thanks

**Comment by fhamborg** [comment] 2020-04-10 10:05
Sounds like a great idea! I guess this could easily be integrated in https://github.com/fhamborg/news-please/blob/2b55c2979806fce49c0c4d2aed8dd5cf73ae76f8/newsplease/crawler/commoncrawl_crawler.py#L249 (or somewhere close to that; specifically, before downloading the file). Unfortunately, I currently don't have time to implement and test this, but if you want to give it a try, I'd again gladly review a PR! :-)

**Comment by ozgurakyazi** [comment] 2020-04-10 12:43
Great :+1: 
Ok I am on it :)

**Comment by fhamborg** [comment] 2020-04-24 13:18
Any luck? :)

**Comment by moyid** [comment] 2020-04-25 20:22
Hi, I am having the same issue, and I created a PR for this.

**Comment by fhamborg** [comment] 2020-04-28 08:27
fixed with moyid's PR

**Closed by fhamborg** 2020-04-28 08:27 UTC

**Comment by copperwiring** [comment] 2023-08-04 13:01
@ozgurakyazi @fhamborg I was checking this issue and after the PR merge, I think it should work as intended i.e. dowload the dates requested. But in my case, it only downloads 2016 file and get 503 error for others. I understand 503 error can be network error but unsure why it **always** downloads 2016 file? 
 Code:

```
# start date (if None, any date is OK as start date), as datetime
my_filter_start_date = datetime.datetime(2022, 1, 1)
# end date (if None, any date is OK as end date), as datetime
my_filter_end_date = datetime.datetime(2022, 12, 31)
# Only .warc files published within [my_warc_files_start_date, my_warc_files_end_date) will be downloaded.
# Note that the date a warc file has been published does not imply it contains only news
# articles from that date. Instead, you must assume that the warc file can contain articlesc
# from ANY time before the warc file was published, e.g., a warc file published in August 2020
# may contain news articles from December 2016.
my_warc_files_start_date = datetime.datetime(2021, 1, 1)
my_warc_files_end_date = datetime.datetime(2023, 6, 31)
```

Ouput:


> my_local_download_dir_warc=./cc_download_warc/
> my_local_download_dir_article=./cc_download_articles/
> my_delete_warc_after_extraction=True
> my_number_of_extraction_processes=1
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to read commoncrawl bucket, using monthly WARC file listings
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2016/08/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2016/09/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2016/11/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2017/10/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2017/11/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2017/12/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2018/01/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2018/02/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2018/12/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2019/01/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2019/02/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2019/03/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2019/04/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2019/05/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2020/07/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2021/01/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2021/02/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2021/03/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2021/04/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2021/06/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2022/02/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2022/03/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2022/11/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2022/12/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2023/07/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Failed to fetch WARC file list https://data.commoncrawl.org/crawl-data/CC-NEWS/2023/08/warc.paths.gz: <Response [503]>
> INFO:newsplease.crawler.commoncrawl_crawler:Found 24308 WARC files
> INFO:newsplease.crawler.commoncrawl_crawler:found 24308 files at commoncrawl.org
> INFO:newsplease.crawler.commoncrawl_crawler:creating extraction process pool with 1 processes
> INFO:newsplease.crawler.commoncrawl_extractor:downloading https://data.commoncrawl.org/crawl-data/CC-NEWS/2016/10/CC-NEWS-20161001122244-00007.warc.gz (local: ./cc_download_warc/crawl-data%2FCC-NEWS%2F2016%2F10%2FCC-NEWS-20161001122244-00007.warc.gz)
