### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by sara-02** [fhamborg/news-please#229] opened 2022-06-08 18:53 UTC
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.
* [x] I confirm that this bug report does not report on a specific news site where news-please does not work. Please keep in mind that news-please is a generic crawler so it is expected that it will not work for all sites well or even at all. 

**Describe the bug**
When running news-please crawler for WARC and filter dates "2020/1/1" to "2020/4/1." and a set of filter host urls I am get the "URL Resolution" error (after some point) of the programming running fine.

**To Reproduce**
1. Add filter dates (on URL and WARC). 
2. Add the following filter list: 
```
    filter_list = [
        "ndtv.com",
        "indiatimes.com",
        "indiatoday.in",
        "thehindu.com",
        "news18.com",
        "indianexpress.com",
        "bbc.com",
        "reuters.com",
        "zeenews.india.com",
        "outlook.com",
        "hindustantimes.com",
        "aljazeera.com"
    ]
```
3. A slightly modified version of the crawler file that I am running is shared [here](https://gist.github.com/sara-02/fa895c4bf367caa140bbb36b68bdfbf5).  

**Expected behavior**
The downloading of articles should occur as expected.

**Log**
A part fo the log trace for last 200 lines before the error occurred and program stopped.
```
INFO:newsplease.crawler.commoncrawl_extractor:statistics
INFO:newsplease.crawler.commoncrawl_extractor:pass = 436, discard = 38254, error = 0, total = 38690
INFO:newsplease.crawler.commoncrawl_extractor:extraction from current WARC file started 1 minute, 58 seconds ago; 0.003052 s/article
INFO:newsplease.crawler.commoncrawl_extractor:article discard (https://www.welt.de/regionales/hessen/article205078328/75-Jaehrige-faehrt-auf-Fussgaengerbruecken-3000-Euro-Schaden.html)
INFO:newsplease.crawler.commoncrawl_extractor:article discard (https://www.latimes.com/entertainment-arts/books/story/2020-01-16/american-dirt-jeanine-cummins-pam-houston)
INFO:newsplease.crawler.commoncrawl_crawler:warc processing statistics
INFO:newsplease.crawler.commoncrawl_crawler:warc files skipped = 0, processed = 7, remaining = 1271, total = 1278
INFO:newsplease.crawler.commoncrawl_crawler:global [s/article] = 0.190833
INFO:newsplease.crawler.commoncrawl_crawler:global [h/warc] = 0.293
INFO:newsplease.crawler.commoncrawl_crawler:estimated remaining time [h] = 4337.815127
1023M / 1023Mmultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/hdd1/news-please/newsplease/crawler/commoncrawl_crawler.py", line 325, in __start_commoncrawl_extractor
    fetch_images=fetch_images)
  File "/mnt/hdd1/news-please/newsplease/crawler/commoncrawl_extractor.py", line 359, in extract_from_commoncrawl
    self.__run()
  File "/mnt/hdd1/news-please/newsplease/crawler/commoncrawl_extractor.py", line 300, in __run
    local_path_name = self.__download(self.__warc_path)
  File "/mnt/hdd1/news-please/newsplease/crawler/commoncrawl_extractor.py", line 210, in __download
    urllib.request.urlretrieve(url, local_filepath, reporthook=self.__on_download_progress_update)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/hdd1/news-please/newsplease/examples/commoncrawl.py", line 239, in <module>
    main()
  File "/mnt/hdd1/news-please/newsplease/examples/commoncrawl.py", line 235, in main
    dry_run=my_dry_run)
  File "/mnt/hdd1/news-please/newsplease/crawler/commoncrawl_crawler.py", line 411, in crawl_from_commoncrawl
    warc_paths)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

```

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version: 3.6
 - news-please: latest github clone

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [x] academic
* [ ] business
* [ ] other
* Some information on your project:

**Comment by fhamborg** [comment] 2022-07-06 10:37
Hi, as we can see from the stacktrace, the issue is thrown in urllib / requests, which is beyond the control of news-please, so I'm closing this issue. FYI: I think this issue is caused by a misconfiguration of your system or problems with the network connection. In case you think this is an actual bug, please open a bug report with urllib / requests.

**Closed by fhamborg** 2022-07-06 10:37 UTC
