### ISSUE TITLE
Does not work with nytimes?

### ISSUE THREAD

**Issue by yingyingww** [fhamborg/news-please#71] opened 2018-10-26 07:59 UTC
**Describe the bug**
Whenever I tried to extract contents from NYTimes articles, they are random and incomplete. 
I tried on Newspaper Demo page as well for NYTimes articles and I got - "Error converting html to string."

**To Reproduce**
Steps to reproduce the behavior, i.e., provide a minimalist example how to reproduce the error. Include a minimalist code example.
If you start with - http://newspaper-demo.herokuapp.com, and put in any NYtimes article, such as https://www.nytimes.com/2018/10/25/business/european-economy.html, you will find the error.

**Expected behavior**
On Demo page, "Error converting html to string."

If this were run in a program or terminal, random words would appear.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. MacOS 10.2]
 - Python Version [e.g. 3.6]
 - news-please Version [e.g. 1.2]

**Comment by fhamborg** [comment] 2018-10-29 18:13
Unfortunately, we cannot help with this issue since it is caused by Newspaper. I suggest that you open an issue at https://github.com/codelucas/newspaper describing this issue. Once they fix the issue, it will automatically be fixed in the latest news-please version.

**Closed by fhamborg** 2018-10-29 18:13 UTC
